typedef struct curso Curso;
typedef struct disciplina Disciplina;
Curso *criarCurso(int cod, char *nome_curs, int bloco_curs, int semanas);
int alturaNo(Curso *raiz);
int fatorBalanceamento(Curso *raiz);
int maiorH(int esq_h, int dir_h);
Curso *rotacaoEsquerda(Curso *raiz);
Curso *rotacaoDireita(Curso *raiz);
Curso *balacearCurso(Curso *raiz);
Curso *inserirCurso(Curso *raiz, Curso *novo);
int verificaFolhaCurso(Curso *raiz);
Curso *verificaFilhoCurso(Curso *raiz);
Curso *verificaMaiorFilho(Curso *raiz);
void swapCurso(Curso *raiz,Curso *filho);
Curso *removerCurso(Curso *raiz);
Curso *buscaCursoRemover(Curso *raiz, int codCurso);
void dadosCurso(Curso *raiz);
void imprimirCursos(Curso *raiz);
Disciplina *criaDisciplina(int codDisciplina, char *nome_dsc, int bloco_dsc, int cargaHoraria);
int alturaNoDsc(Disciplina *raiz);
Disciplina *RotacaoEsquerdaDsc(Disciplina *raizD);
Disciplina *RotacaoDireitaDsc(Disciplina *raizD);
Disciplina *BalancearNoDisciplina(Disciplina *raizD);
int fatorBalanceamentoDisciplina(Disciplina *raizD);
Disciplina *inserirDisciplina(Disciplina *raiz,Disciplina *novo);
void inserirDisciplinaCurso(Curso **raiz,int codCurso,Disciplina *novo);
int verificaNoFolha(Disciplina *raizD);
Disciplina *verificaUmFilho(Disciplina *raizD);
Disciplina* maiorFilhoEsquerda(Disciplina* raizD);
void swap(Disciplina *raizD, Disciplina *no);
Disciplina *removerDisciplina(Disciplina *raiz,int codDsc);
void buscarCursoRemoverDsc(Curso **raiz,int codCurso,int codDsc);
void dadosDisciplina(Disciplina *raizD);
void imprimirDisciplinas(Disciplina *raizD);
void imprimirDisciplinasEmOrdem(Curso *raiz,int codCurso);
void imprimirCursoEspecifico(Curso *raiz,int cod);
void ImprimirCursoBloco(Curso *raiz,int blocos);
void buscaDisciplinaPorCodigo(Disciplina *raizD, int codDisciplina);
void imprimirDisciplinaEspecifica(Curso *raiz, int codCurso, int codDisciplina);
void imprimirDisciplinasBloco(Disciplina *raiz, int bloco);
void imprimirDisciplinasDoBloco(Curso *raiz,int cod,int bloco);
void buscaDisciplnasPorCargaH(Disciplina *raizD, int c_horaria);
void imprimirDisciplinasPelaCargaH(Curso *raiz, int codCurso,int c_horaria);